### PR TITLE
Project Proposal

### PR DESCRIPTION
**Pull request by vlee98**

### CODE REVIEW

**Comment by eshellman** [comment]
Thanks for this proposal!

Food for thought:
1. Is a React front-end going to work well with the sort of client devices found in environments where there is limited availability of internet?
2. Does the Internet-in-a-box platform support user accounts?
3. Should PG-in-a-Box support downloads or focus on html presentation? What might be the reading environment?
4. What does "scaleable" mean in the context of Internet-in-a-box?
5. What might be the privacy implications of providing "recently viewed" and "trending" on servers serving small communities?

**Comment by vlee98** [comment]
Thank you for the feedback!

We've tried to come up with some more ideas that we think would be a bit more practical.

**Comment by eshellman** [comment]
Thanks for the updates!

**Comment by eshellman** [comment]
As there are two strong teams interested in this area, I note that there is a related project which I pitched last year (without success) that may interest you copyright-renewals.md

**Pull request merged**
