### PR TITLE
Team proposal for the 2021-2022 project

### PR DESCRIPTION
**Pull request by brogan20**

### CODE REVIEW

**Comment by eshellman** [comment]
Hi, thanks for your interest! Would you like to schedule a zoom call or similar?

**Comment by brogan20** [comment]
Hi Eric, we'd be available to call before 2 on Wednesday or after 2 on Friday.

**Comment by eshellman** [comment]
1PM tomorrow, Wednesday?

**Comment by brogan20** [comment]
Sure thing! My email is bclemen1@stevens.edu if you want to send a zoom link without sharing it on GitHub.

**Comment by eshellman** [comment]
I'm looking forward to working with you. Please send me emails for the team so I can set you up in Slack

**Pull request merged**
